### ISSUE TITLE
Cannot interact with dispenser?

### ISSUE THREAD

**Issue by sjavi4** [NUTT1101/CatchBall#8]
CatchBall will drop as item instead of shooting onto entities and turn into player head

**Comment by NUTT1101** [comment]
Hello, Please write down your plugin and game version here.

**Comment by NUTT1101** [comment]
Please confirm the following details:
- Check you are using 'Dispenser' not 'Dropper'.
- Check the entity catching stage was enabled.

---
This is my test video, you can check it out.
Game version: 1.19.3
Plugin version: v1.1.6
https://youtu.be/pCBEWbMNgpQ

**Comment by sjavi4** [comment]
I found the problem, it was the dispenser shooting the CatchBall too close to the entity (less than 1 block apart), it will pass through the entity and drop as item

**Comment by NUTT1101** [comment]
I have tested. I think that not the plugin bug but that not be detected to hit entity.
I used a normal snowball for testing, It has same problem that you said.
